-- CREAMOS UNA BASE DE DATOS -- 
CREATE DATABASE web;

-- UTILIZAMOS ESA BASE DE DATOS --
USE web;

-- CREAMOS LA TABLA CON LOS CAMPOS --
CREATE estudiante TABLE estudiante(
id INT NOT NULL PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
apellido VARCHAR(30) NOT NULL
);

-- CARGAR DATOS EN LA TABLA DE ESTUDIANTES -- 
INSERT INTO estudiante VALUES (1, "Victoria", "Lopez");
